Repository harundogdu/twitter-clone, pull requests merged in 2023-06, with the labels that each got.

#101 bug-fixed: blank tweet blocking
  components/PostForm.tsx
Labels: bug

#102 V1.0.0/feature/page not found
  components/Sidebar.tsx
  components/shared/Button.tsx
  components/shared/Modal.tsx
  pages/404.tsx
Labels: bug, feature

#103 V1.0.0/feature/tweet action bar modal development
  components/Avatar.tsx
  components/Sidebar.tsx
  components/modals/TweetModal.tsx
  hooks/useTweetActionModal.ts
  pages/_app.tsx
Labels: enhancement, feature

#107 V1.0.0/refactor/404 page styling
  pages/404.tsx
Labels: bug

#109 feat: new photo added
  components/Avatar.tsx
  public/twitter-user-avatar.jpg
Labels: enhancement

#110 feat: magnification
  components/users/UserHero.tsx
Labels: enhancement

#111 feat: scrollbar shaped
  components/Layout.tsx
  package.json
  tailwind.config.js
  yarn.lock
Labels: feature

#125 V1.0.0/refactor/button structures
  base/button.ts
  components/ActionSidebar.tsx
  components/PostForm.tsx
  components/Sidebar.tsx
  components/bottom/Bottom.tsx
  components/modals/LoginModal.tsx
  components/modals/RegisterModal.tsx
  components/modals/TweetModal.tsx
  components/shared/Button.tsx
  components/shared/Modal.tsx
  components/users/UserInfo.tsx
  pages/404.tsx
  tailwind.config.js
Labels: enhancement, help wanted, feature

#126 V1.0.0/refactor/button structures
  base/button.ts
  components/Sidebar.tsx
  components/shared/Button.tsx
  components/users/UserInfo.tsx
  tailwind.config.js
Labels: bug, enhancement, feature

#114 feat: renewed progressbar
  components/PostForm.tsx
  components/modals/TweetModal.tsx
Labels: enhancement

#129 V1.0.0/feature/connect section
  components/ActionSidebar.tsx
  components/shared/Header.tsx
  pages/404.tsx
  pages/api/users/index.ts
  pages/connect.tsx
Labels: enhancement, refactoring, feature

#130 V1.0.0/feature/post edit
  components/posts/PostFeed.tsx
  components/users/UserHero.tsx
  pages/404.tsx
  tailwind.config.js
Labels: enhancement, refactoring, feature
