Repository harundogdu/twitter-clone, pull requests merged in 2023-05, with the labels that each got.

#21 fix: readme updated
  README.md
Labels: documentation

#22 feat: Added password display icon
  components/shared/Input.tsx
Labels: feature

#23 feat: Edited and added dynamic title and favicon
  pages/_app.tsx
  public/twitter-favicon.ico
Labels: feature

#31 fix: Installing area edited
  README.md
Labels: documentation

#39 feat: Built with update
  README.md
Labels: documentation

#37 feat: added link to bio
  components/users/UserInfo.tsx
Labels: feature

#55 feat: login with username defined
  components/modals/LoginModal.tsx
  components/modals/RegisterModal.tsx
  components/shared/Input.tsx
  pages/api/auth/[...nextauth].ts
Labels: feature

#63 doc: readme updated
  README.md
Labels: documentation

#67 V.1.0.0/feature/profile image view
  components/Avatar.tsx
  components/Layout.tsx
  components/shared/Portal.tsx
  components/users/UserHero.tsx
  pages/_app.tsx
Labels: enhancement, feature

#70 V1.0.0 up/feature/view profile picture
  components/Avatar.tsx
  components/users/UserHero.tsx
Labels: enhancement, feature

#71 fix: correction
  pages/users/[username].tsx
Labels: bug

#62 bugfix: General expression arrangement
  components/shared/Input.tsx
  utils.js
Labels: bug

#72 feat: while viewing image user can close image with click non image area
  components/users/UserHero.tsx
Labels: enhancement, feature

#76 V1.0.0/feature/utils structure
  components/shared/Input.tsx
  utils.js
  utils/helpers.ts
Labels: enhancement

#78 V1.0.0/feature/responsive profile photo
  components/Avatar.tsx
  components/users/UserHero.tsx
  tailwind.config.js
  utils/enums.ts
Labels: enhancement, feature

#79 feat: loading definition inside the page
  components/posts/PostFeeds.tsx
Labels: feature

#83 V1.0.0/bug fix/profile button
  components/SidebarItem.tsx
  components/posts/PostFeeds.tsx
Labels: bug

#86 fix: default profile pictures can be view
  components/users/UserHero.tsx
Labels: bug

#87 feat: Added counter to tweeting forehead
  components/PostForm.tsx
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement, feature

#84 fixed: sidebar action renewed
  components/ActionSidebar.tsx
  components/Sidebar.tsx
Labels: feature

#77 V1.0.0/sub bio detail
  components/modals/EditModal.tsx
  components/posts/PostFeed.tsx
  components/shared/BasicDatePicker.tsx
  components/users/UserInfo.tsx
  package-lock.json
  package.json
  pages/api/edit.ts
  prisma/schema.prisma
  types/user.type.ts
  utils/helpers.ts
  yarn.lock
Labels: feature

#93 V1.0.0/bug fix/routing errors
  components/ActionSidebar.tsx
  components/Avatar.tsx
  components/posts/PostFeed.tsx
Labels: bug

#98 feat: 404 pages styling
  pages/404.tsx
Labels: enhancement, feature
