Repository harundogdu/twitter-clone, pull requests merged in 2023-07, with the labels that each got.

#133 V1.0.0/feature/action sidebar footer
  components/ActionSidebar.tsx
  components/modals/LoginModal.tsx
  components/posts/PostFeed.tsx
  hooks/useFollow.ts
Labels: enhancement, refactoring, feature

#135 feat: loading status on user posts
  components/posts/PostFeeds.tsx
Labels: enhancement, feature

#139 V1.0.0/feature/readme update
  README.md
  components/ActionSidebar.tsx
  components/modals/RegisterModal.tsx
  components/posts/PostFeeds.tsx
  pages/connect.tsx
Labels: documentation

#138 V.1.0.0/feature/searchbar feature
  components/ActionSidebar.tsx
  components/Layout.tsx
  components/Searchbar.tsx
  components/WhoToFollow.tsx
  hooks/useSearch.ts
  package-lock.json
  package.json
  pages/api/search.ts
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: enhancement, feature

#146 feat: sticky
  components/ActionSidebar.tsx
  components/Searchbar.tsx
  components/WhoToFollow.tsx
Labels: bug, enhancement, feature

#150 Enter key arrangement
  components/modals/LoginModal.tsx
  components/shared/Modal.tsx
Labels: bug

#159 feat: footer format editing
  components/WhoToFollow.tsx
Labels: enhancement

#166 Ae/feature/153/bugs in the project
  components/Searchbar.tsx
  components/posts/PostFeed.tsx
  components/shared/Button.tsx
  components/users/UserInfo.tsx
Labels: bug, feature, fix
